version: '3.8'

services:
  ytb-studio:
    build: .
    container_name: ytb-studio
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    environment:
      - DOWNLOADS_DIR=/app/downloads
